#!/usr/bin/env python3
"""Export a ModelForge-compatible PEFT receipt from DomainForge eval outputs.

Usage (from domainforge-rag-peft root, after GPU pipeline + eval-compare):

  python scripts/export_modelforge_receipt.py \\
    --s0 data/eval/results/s0_baseline.json \\
    --s3 data/eval/results/s3_peft_hybrid.json \\
    --s4 data/eval/results/s4_dpo_peft.json \\
    --adapter-uri adapters/s4-dpo \\
    --out /path/to/modelforge-llmops/docs/receipts/peft_gpu.json
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _metric(blob: dict[str, Any], *keys: str, default: float = 0.0) -> float:
    for k in keys:
        if k in blob and isinstance(blob[k], (int, float)):
            return float(blob[k])
        # nested common shapes
        summary = blob.get("summary") or blob.get("metrics") or {}
        if isinstance(summary, dict) and k in summary:
            return float(summary[k])
    return default


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--s0", type=Path, required=True)
    p.add_argument("--s3", type=Path, required=True)
    p.add_argument("--s4", type=Path, required=True)
    p.add_argument("--base-model", default="mistralai/Mistral-7B-Instruct-v0.3")
    p.add_argument("--gpu", default="1x CUDA (operator-reported)")
    p.add_argument("--adapter-uri", default="")
    p.add_argument("--sft-examples", type=int, default=0)
    p.add_argument("--dpo-pairs", type=int, default=0)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()

    s0 = json.loads(args.s0.read_text())
    s3 = json.loads(args.s3.read_text())
    s4 = json.loads(args.s4.read_text())

    receipt = {
        "status": "gpu",
        "honesty": "CUDA PEFT receipt — requires operator GPU run; not peft_smoke.",
        "run_id": f"peft-{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}",
        "base_model": args.base_model,
        "gpu": args.gpu,
        "sft_examples": args.sft_examples,
        "dpo_pairs": args.dpo_pairs,
        "metrics": {
            "S0_schema_pass": _metric(s0, "schema_pass", "format_adherence", "json_valid_rate"),
            "S3_schema_pass": _metric(s3, "schema_pass", "format_adherence", "json_valid_rate"),
            "S4_schema_pass": _metric(s4, "schema_pass", "format_adherence", "json_valid_rate"),
            "S4_preference_win_rate": _metric(s4, "preference_win_rate", "win_rate", "dpo_win_rate"),
        },
        "adapter_uri": args.adapter_uri,
        "notes": "RAG still owns facts; PEFT owns schema/behavior (ADR-019/020). Generated by DomainForge export_modelforge_receipt.py.",
        "sources": {
            "s0": str(args.s0),
            "s3": str(args.s3),
            "s4": str(args.s4),
        },
    }
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(receipt, indent=2) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
